# Generated by Django 5.0.3 on 2024-03-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.postmodel')),
            ],
        ),
    ]
