# Generated by Django 4.2.7 on 2024-03-18 10:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='profile_posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=django_resized.forms.ResizedImageField(crop=None, default='anon.png', force_format=None, keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='stories'),
        ),
    ]
