# Generated by Django 5.0.1 on 2024-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followermodel',
            name='follower',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='followermodel',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
