# Generated by Django 5.0.1 on 2024-03-19 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_alter_postmodel_image_alter_profile_profile_pics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
