# Generated by Django 5.0.1 on 2024-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_rename_likefilter_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='postID',
            field=models.IntegerField(),
        ),
    ]
