# Generated by Django 5.0.2 on 2024-04-12 08:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_alter_story_options_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='profile_images'),
        ),
    ]
