# Generated by Django 5.0.3 on 2024-03-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_postmodel_num_of_comments_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='caption',
        ),
    ]
