# Generated by Django 5.0.3 on 2024-03-30 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_remove_story_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 15, 53, 46, 8732)),
        ),
    ]
