# Generated by Django 4.2.7 on 2024-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_alter_profile_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='anon.png', upload_to='profile_images'),
        ),
    ]
