# Generated by Django 5.0.1 on 2024-03-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_story_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
    ]
