# Generated by Django 5.0.1 on 2024-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_followermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
