# Generated by Django 5.0.1 on 2024-03-04 18:01

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_alter_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='current_user', max_length=150),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[400, 400], upload_to='profile_posts'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=django_resized.forms.ResizedImageField(crop=None, default='anon.png', force_format=None, keep_meta=True, quality=70, scale=None, size=[300, 300], upload_to='profile_images'),
        ),
    ]
