# Generated by Django 5.0.3 on 2024-03-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_alter_story_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location_city',
            new_name='github_url',
        ),
    ]
