# Generated by Django 4.2.7 on 2024-03-07 08:45

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_alter_postmodel_author_alter_postmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[400, 400], upload_to='stories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.profile')),
            ],
        ),
    ]
