# Generated by Django 5.0.3 on 2024-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_rename_location_city_profile_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
