# Generated by Django 4.2.7 on 2024-03-07 11:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[200, 340], upload_to='stories'),
        ),
    ]
