# Generated by Django 4.2.7 on 2024-03-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_alter_postmodel_author_alter_postmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=302),
        ),
    ]
