# Generated by Django 5.0.3 on 2024-03-31 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0009_alter_profile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300, validators=[django.core.validators.URLValidator()]),
        ),
    ]
