# Generated by Django 5.0.1 on 2024-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0009_likefilter_post_author_post_num_of_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModel',
        ),
    ]
