# Generated by Django 5.0.2 on 2024-04-01 15:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0010_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[300, 400], upload_to='profile_posts'),
        ),
    ]
